### ISSUE TITLE
pitmp mixing reports of different modules

### ISSUE THREAD

**Issue by pedrorijo91** [STAMP-project/pitmp-maven-plugin#17]
I have a maven project with 3 modules. One of them is ignored through `skippedModules` configuration. The remaining 2 are getting different results from when I run pit directly on each module.

I was debugging the problem and I've found that on one of the modules report I have a few packages listed that belong to the other module. Is this a known issue? is there something missing me? Will try to provide a reproducible, but may take some time. Just wanted to get some early feedback.

Using pitmp version 1.3.4

**Comment by pedrorijo91** [comment]
ps: plugin configuration

```
          <plugin>
                <groupId>eu.stamp-project</groupId>
                <artifactId>pitmp-maven-plugin</artifactId>
                <version>1.3.4</version>
                <configuration>
                    <skippedModules>
                        <param>a-module</param>
                    </skippedModules>
                    <mutateStaticInitializers>true</mutateStaticInitializers>
                    <mutators>
                        <mutator>ALL</mutator>
                    </mutators>
                    <excludedMethods>
                        <param>toString</param>
                        <param>toStringHelper</param>
                        <param>hashCode</param>
                        <param>equals</param>
                    </excludedMethods>
                    <excludedClasses>
                        <param>some.package.Klass</param>
                    </excludedClasses>
                    <mutationThreshold>70</mutationThreshold>
                    <threads>2</threads>
                </configuration>
            </plugin>
```

**Comment by pedrorijo91** [comment]
any idea on this @CaelInria ?

**Comment by Cael35** [comment]
skippedModules is related to test execution, not to classes to be mutated. I'll probably rename it, cf #27.

**Comment by pedrorijo91** [comment]
kinda of confused. Is there any setting to specify which modules should PIT look at (mutate and run tests) ?

**Comment by Cael35** [comment]
There are new properties available to manage the code to be mutated (https://github.com/STAMP-project/pitmp-maven-plugin#running-pitmp-on-your-project) : targetDependencies / ignoredDependencies
There are include in the next version (1.3.5), which will be released on Monday (waiting for the next release of Descartes)

**Comment by pedrorijo91** [comment]
awesome, thanks! will let you know if it solves the problem, otherwise will create a more reproducible report

**Comment by Cael35** [comment]
v1.3.6 is available.

**Comment by pedrorijo91** [comment]
will test tomorrow :) thanks!

**Comment by pedrorijo91** [comment]
using the`targetDependencies` configuration solved the problem. thanks a lot ;)
