### ISSUE TITLE
Maven build: verify_pitmp.sh fails under Windows

### ISSUE THREAD

**Issue by nrainer** [STAMP-project/pitmp-maven-plugin#21]
#### Characteristics
- **Issue Type**: maintenance
- **Execution Environment**: Windows

verify_pitmp.sh cannot be executed under Windows. Move the execution into a profile.

**Comment by nrainer** [comment]
See pull request https://github.com/STAMP-project/pitmp-maven-plugin/pull/23

**Comment by Cael35** [comment]
PitMP is officially not tested on Windows yet, sorry ! :-)
Should be solved with #11

**Comment by nrainer** [comment]
Ok :)
