### ISSUE TITLE
Skip modules not working as expected

### ISSUE THREAD

**Issue by nrainer** [STAMP-project/pitmp-maven-plugin#22]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major

#### Description
Code from skipped modules is mutated.

**Comment by nrainer** [comment]
See pull request https://github.com/STAMP-project/pitmp-maven-plugin/pull/25

**Comment by sushantchoudhary** [comment]
Awesome, thanks for prioritizing this @nrainer . I tested the behavior on master and it works like a charm. Do you plan to bump the version soon in maven central?

**Comment by nrainer** [comment]
PR has been merged.
