### ISSUE TITLE
Rename configuration parameters targetModules and skipModules?

### ISSUE THREAD

**Issue by nrainer** [STAMP-project/pitmp-maven-plugin#27]
#### Characteristics
- **Issue Type**: maintenance

#### Description
I just found out that these parameters might be confusing after the last fix.
`skipModules` excludes tests from a given module and ensures that no code is fetched from the module (since fix #22). However, `targetModules` was not adjusted by #22 and includes tests from the specified modules without filtering the code. The difference between these two parameters might be unexpected.

#### Proposal
* Shall we remove the `skipModules` parameter and replace it by `skipTestsFromModules` and `skipCodeFromModules`?
* Do we need a migration or something similar for that?
* Do we need `targetModules`? Is this often used? If not, can it be removed? Shall it be split similarily otherwise?

Any thoughts on this?

**Comment by Cael35** [comment]
Originally targetModules and skippedModules were related to test execution, it would probably be better to rename them, and to have also properties to skip or specify classes to be mutated.
It may be useful to have the options to specify either modules to be skipped or processed. Depending of the size of the project, having only targetModules can be painful. :-)
I'll try to fix this in the next release.

**Comment by nrainer** [comment]
Sounds good to me. :)

**Comment by Cael35** [comment]
I kept targetModules and skippedModules to manage directories where to run PIT, and I added new properties to manage the code to be mutated (https://github.com/STAMP-project/pitmp-maven-plugin#running-pitmp-on-your-project) : targetDependencies / ignoredDependencies
There are include in the next version (1.3.5), which will be released on Monday (waiting for the next release of Descartes)
But if you can't wait to use it, 1.3.5-SNAPSHOT is up to date and is tested with PIT 1.4.2 and Descartes 1.2.4 :-)

**Comment by nrainer** [comment]
Great, thank you!
