### ISSUE TITLE
Can't specify outputFormats for Descartes (or feature undocumented ?)

### ISSUE THREAD

**Issue by gibello** [STAMP-project/pitmp-maven-plugin#44]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [minor]
- **Tool/Service/Component**: [pitmp-maven-plugin, descartes]
- **Execution Environment**: [Java 8, Ubuntu linux 18.04]
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.org]

#### Description

Tried to specify outputFormats to pitmp-maven-plugin, as below: it has no effect at all on the generated output (always HTML).
This feature is not documented: is it implemented ? If so, the doc should be updated.

```xml
<plugin>
    <groupId>eu.stamp</groupId>
    <artifactId>pitmp-maven-plugin</artifactId>
    <version>1.3.7-SNAPSHOT</version>
    <configuration>
      <mutationEngine>descartes</mutationEngine>
      <outputFormats>
        <value>HTML</value>
        <value>JSON</value>
        <value>METHODS</value>
        <value>ISSUES</value>
      </outputFormats>
    </configuration>
  </plugin>
```

**Comment by oscarlvp** [comment]
I've tried the configuration and it works on my side. Two things to notice:
1. The other reports are created in the root directory of the `HTML` report
2. The configuration you report as `eu.stamp` instead of `eu.stamp-project`

**Comment by gibello** [comment]
Looks fine, due to the wrong config you mentioned ? Thanks.
