### ISSUE TITLE
skip modules doesn't work

### ISSUE THREAD

**Issue by yilativs** [STAMP-project/pitmp-maven-plugin#45]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [block]
- **Tool/Service/Component**: [1.3.6]
- **Execution Environment**: [java8, linux]
- **Reporter**: [Vitaliy]

#### Description
It is unclear from documentation, how to properly specify skippedModules 
(I tried all possible options) and none seems to work.
in order to exclude foo-module1 I've tried both maven2 and maven3 style params, groupId:artifactId and module name

<skippedModules>
	<param>foo-module1</param>
	<param>org.foo:foo-module1</param>
	<skippedModule>foo-module1</skippedModule>
	<skippedModule>org.foo:foo-module1</skippedModule>
</skippedModules>

#### Steps to reproduce
git clone https://github.com/yilativs/pitmp-multi-module-sample.git
cd pitmp-multi-module-sample
mvn eu.stamp-project:pitmp-maven-plugin:run

expected result: foo-module1 is skipped
result: plugin runs pit mutations for foo-module1

**Comment by Cael35** [comment]
I tried with the command line:
`mvn "-DskippedModules=foo-module1" eu.stamp-project:pitmp-maven-plugin:run`
and it workded.
So I add a look in the pom.xml and I think the problem comes from the duplicated tags `<configuration>...</configuration>`.  
I replaced:
![image](https://user-images.githubusercontent.com/25077761/53804159-09bb2b80-3f47-11e9-861f-30570b320f72.png)  
with:
![image](https://user-images.githubusercontent.com/25077761/53804089-d6789c80-3f46-11e9-90eb-2c2c8daf82cc.png)  
and it worked.  
Let me know if it works for you too. :-)

**Comment by yilativs** [comment]
command line paramet skipModules works but changing configuration does not. 

I've added a sample for you https://github.com/yilativs/pitmp-multi-module-sample/tree/skip-via-param-tag

executing:
 mvn package -DskipTests eu.stamp-project:pitmp-maven-plugin:run
will fail build because module 1 tests will be executed ( i intentionally added a test there that will fail)

executing:
 mvn package -DskipTests
won't fail, because tests will be skipped because of a bag either in configruation
or in maven plugin

executing:
mvn "-DskippedModules=foo-module1" eu.stamp-project:pitmp-maven-plugin:run
works, skippedModuled parameter works

**Comment by Cael35** [comment]
There's still duplicated marks in the file pom.xml :-)
```
		<configuration>
			<configuration>          <!-- DUPLICATED -->
				<skippedModules>
					<param>foo-module1</param>
				</skippedModules>
				...
			</configuration>         <!-- DUPLICATED -->
		</configuration>
``` 

Remove those 2 lines from the pom.xml:  
* https://github.com/yilativs/pitmp-multi-module-sample/blob/1262e590289fd051dc758f91b414b23997ac029a/pom.xml#L26  
* https://github.com/yilativs/pitmp-multi-module-sample/blob/1262e590289fd051dc758f91b414b23997ac029a/pom.xml#L34

**Comment by yilativs** [comment]
I tried it and it works with both <skippedModule> and <param> tags to specify the required module to be skipped.
This wasn't a bug but my misconfiguration.
Thank you very much for support!
