### ISSUE TITLE
mvn install fails on first try

### ISSUE THREAD

**Issue by n-a-sz** [STAMP-project/pitmp-maven-plugin#5]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: pitmp-maven-plugin 1.1.1
- **Execution Environment**: Win10, maven 3.0.5
- **Reporter**: András Szabolcs Nagy

#### Description
I've just cloned the reopsitory and have tried to install it with `mvn install` but failed instantly with the message: 

> Error extracting plugin descriptor: 'No mojo definitions were found for plugin: eu.stamp:pitmp-maven-plugin.'

#### Steps to reproduce

```
git clone https://github.com/STAMP-project/pitmp-maven-plugin.git
cd pitmp-maven-plugin
git checkout 1.1.1
mvn install
```

#### Possible solution
I've found the following on stackoverflow: https://stackoverflow.com/a/18999968
Adding the following to the pom xml, has worked for me:

```
  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-plugin-plugin</artifactId>
            <version>3.2</version>
            <configuration>
                <goalPrefix>pitmp</goalPrefix>
            </configuration>
            <executions>
                <execution>
                    <id>default-descriptor</id>
                    <goals>
                        <goal>descriptor</goal>
                    </goals>
                    <phase>process-classes</phase>
                </execution>
                <execution>
                    <id>help-descriptor</id>
                    <goals>
                        <goal>helpmojo</goal>
                    </goals>
                    <phase>process-classes</phase>
                </execution>
            </executions>
        </plugin>
    </plugins>
  </build>
```

**Comment by Cael35** [comment]
Hello,

I don't have this issue with Maven 3.3.9. I'll try to reproduce and I'll provide a corrected release.

Thanks for your help ! :-)

**Comment by n-a-sz** [comment]
Thank you very much! Unfortunately, I cannot upgrade my maven due to maven plugin dependencies :(

**Comment by n-a-sz** [comment]
It has turned out, I could upgrade my maven as our dependency is no longer causing problems with newer versions of maven (though this became true only a month ago, I feel lucky :) ). Now, it works for me.

**Comment by Cael35** [comment]
Thanks for reporting ! :-)
