### ISSUE TITLE
Nullpointer exception when no target classes are found

### ISSUE THREAD

**Issue by n-a-sz** [STAMP-project/pitmp-maven-plugin#6]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: pitmp-maven-plugin 1.1.1
- **Execution Environment**: Win10, maven 3.5.3 (also tested with maven 3.0.5)
- **Reporter**: András Szabolcs Nagy

#### Description
I got a NullPointerException from PmpMojo.java at line 166. I assume the local variable `moduleList` is null. It can happen when no targetClass is provided and the condition at line 151 returns true. In this case the moduleList is not initialized hence the NPE.

It seems the `else` keyword (at line 160 without scope) could be removed. (I did this and it seems to work now).

#### Steps to reproduce
I have just followed the instructions on the main site, maybe I misconfigured the pom.xml somehow as I did provide the `<targetClasses>` configuration.

**Comment by Cael35** [comment]
Hello @n-a-sz ,

This issue is fixed in the release 1.1.5 available in Maven Central.
Unfortunately there is still a bug: if you don't specify any targetClass, no mutation are found. I created an issue for it (#10).

**Comment by n-a-sz** [comment]
Thank you @CaelInria !

**Comment by Cael35** [comment]
Szivesen @n-a-sz ! :-)
